export enum strings {
  'ADD_TO_BAG' = 'Add to bag',
  'ADD_TO_WISH_LIST' = 'Add to wishlist',
  'ARTICLE' = 'Article',
  'BRAND_NAME' = 'ANDALE TEMPO',
  'ITEM' = 'ITEM',
  'SUPPLIER_COLOR' = 'Supplier color:',
  'HOME' = 'Home',
  'MENSWEAR' = 'Menswear',
  'ORDER_TOTAL' = 'Order Total',
  'PLEASE_SELECT_A_SIZE' = 'PLEASE SELECT A SIZE.',
  'RECENTLY_VIEWED' = 'RECENTLY VIEWED',
  'REMOVE' = 'Remove',
  'SELECT_A_SIZE' = 'SELECT A SIZE',
  'SIZE' = 'SIZE:',
  'SHOPPING_CART' = 'SHOPPING CART',
  'TOTAL' = 'TOTAL',
  'WOMENWEAR' = 'Womenwear',
}
